### ISSUE TITLE
fix link to open new issue

### ISSUE THREAD

**Issue by DeanLa** [eyaltrabelsi/pandas-log#16]
# Brief Description of Fix

Currently, the link to submit an issue refers to ericmjl. probably from a template cookie cutter.

I would like to propose a change, such that now the docs...

# Relevant Context
![image](https://user-images.githubusercontent.com/7852981/67457178-9d0eb180-f63b-11e9-9674-c68d8816c1fd.png)

[readthedocs contributing page](https://pandas-log.readthedocs.io/en/latest/contributing.html)

- [Link to documentation page](https://pandas-log.readthedocs.io)

**Comment by eyaltrabelsi** [comment]
@DeanLa will fix.

**Comment by eyaltrabelsi** [comment]
[fixed](https://github.com/eyaltrabelsi/pandas-log/pull/18)
